name: pdfarranger
base: core22
adopt-info: pdfarranger
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  - build-on: arm64

slots:
  pdfarranger:
    interface: dbus
    bus: session
    name: com.github.jeromerobert.pdfarranger

plugs:
  shared-memory:
    private: true

apps:
  pdfarranger:
    command: bin/pdfarranger
    extensions: [gnome]
    plugs:
      - home
      - network
      - optical-drive
      - removable-media
    common-id: com.github.jeromerobert.pdfarranger
    desktop: share/applications/com.github.jeromerobert.pdfarranger.desktop
   
   
parts:
  pdfarranger:
    plugin: python
    source: https://github.com/pdfarranger/pdfarranger.git
    parse-info: [usr/share/metainfo/com.github.jeromerobert.pdfarranger.metainfo.xml]
    source-tag: 1.9.2 
    python-packages:
      - distutils-extra-python==2.39.2
      #- img2pdf==0.4.4
      - lxml==4.9.2
      - packaging==23.1
      - pillow==9.5.0
      - pybind11==2.10.4
      - setuptools-scm==7.1.0
      - tomli==2.0.1
      - typing_extensions==4.6.3
      - deprecation==2.1.0
      - pikepdf==7.2.0
      - python_dateutil==2.8.2
      - wheel
    build-environment:
      # WORKAROUND: The python plugin is broken with gnome extension
      - PATH: ${CRAFT_PART_INSTALL}/bin:${PATH}
      - PYTHONPATH: ""
    build-packages:
      - intltool
      - python3-img2pdf
    stage-packages:
      - gir1.2-poppler-0.18
      - libpoppler-glib8
      - libqpdf28
    prime:
      # WORKAROUND: Skip venv from python plugin
      - -bin/activate
      - -bin/activate.csh
      - -bin/activate.fish
      - -bin/Activate.ps1
      - -bin/python
      - -bin/python3
      - -bin/python3.10
      - -bin/pip
      - -bin/pip3
      - -bin/pip3.10
      - -pyvenv.cfg
